package com.poly.logger;

public enum MsgInLog {

    SUCCESS("SUCCESS"),
    INVALID_ARGUMENTS("INVALID_ARGUMENTS"),
    FAILED_TO_WRITE("FAILED_TO_WRITE"),
    FAILED_TO_READ("FAILED_TO_READ"),
    INVALID_INPUT_STREAM("INVALID_INPUT_STREAM"),
    INVALID_OUTPUT_STREAM("INVALID_OUTPUT_STREAM"),
    CONFIG_GRAMMAR_ERROR("CONFIG_GRAMMAR_ERROR"),
    CONFIG_SEMANTIC_ERROR("CONFIG_SEMANTIC_ERROR"),
    FAILED_PIPELINE_CONSTRUCTION("FAILED_PIPELINE_CONSTRUCTION"),
    NOT_FOUND_TOKEN("NOT_FOUND_TOKEN: "),

    NO_CONFIG_FILE("NO_CONFIG_FILE"),
    START_PARS("START_PARS"),
    INCORRECT_NUM_OF_ARGUMENTS("INCORRECT_NUM_OF_ARGUMENTS"),
    INVALID_EXPRESSION("INVALID_EXPRESSION"),
    INVALID_CONFIG_DATA("INVALID_CONFIG_DATA"),
    TRY_CREATE_WORKER("TRY_CREATE_WORKER");

    private final String msg;

    public String getMsg() {
        return msg;
    }

    MsgInLog(String errorMsg) {
        this.msg =  errorMsg;
    }
}
